"""
RallyIQ — все тексты интерфейса на трёх языках.
Казахский написан правильной кириллицей.
"""

TEXTS = {
    "ru": {
        "welcome": "Привет, {name}!\n\n🏸 RallyIQ — твой AI-тренер по бадминтону.\n\nЗагружаешь видео матча → получаешь разбор:\n• Сильные стороны\n• Технические ошибки\n• Тактика\n• Упражнения\n\n💳 Баланс: {credits} анализов",
        "help": "🏸 Как пользоваться:\n\nНажми кнопки внизу экрана:\n🏸 Анализ — разбор видео\n💳 Купить — пакеты анализов\n💰 Баланс — сколько осталось\n🌐 Язык — сменить язык\n\nФорматы видео:\n• Файл прямо в чат (до 50МБ)\n• Google Drive ссылка (любой размер)",
        "buy_text": "💳 Выбери пакет анализов:\n\n⭐ Оплата звёздами Telegram (Stars).\n🎁 Первый анализ всегда бесплатный.",
        "btn_analyze": "🏸 Начать анализ",
        "btn_buy": "💳 Купить анализы",
        "paid_ok": "✅ Добавлено 5 анализов!\nБаланс: {credits}",
        "free_ok": "🎁 Бесплатный анализ добавлен!\nНажми «Начать анализ».",
        "free_used": "❌ Бесплатный анализ уже использован.\nНажми «Купить анализы».",
        "balance": "💳 Твой баланс: {credits} анализов",
        "no_credits": "❌ У тебя нет анализов.\n\n🎁 Первый раз? Жми «Начать анализ» — дам бесплатный\n💳 Или купи пакет",
        "busy": "⏳ Я уже анализирую твоё предыдущее видео. Дождись результата.",
        "ask_shirt": "🏸 Начинаем!\n\nОпиши свою одежду в видео:\nНапример: красная футболка, чёрные шорты",
        "ask_opponent": "✅ Понял: {shirt}\n\nТеперь опиши одежду соперника:",
        "ask_video": "✅ Отлично!\n\nОтправь видео:\n1️⃣ Файл прямо в чат (до 50МБ)\n2️⃣ Google Drive ссылка (любой размер)\n\n💡 Лучше всего: 20-60 секунд активной игры, где тебя хорошо видно\n💡 Drive: открой доступ «всем у кого есть ссылка»\n\n/cancel — отмена",
        "processing": "⏳ Получил! Анализирую... 5-10 минут 🎯",
        "downloading": "⏳ Скачиваю видео...",
        "extracting": "⏳ Извлекаю ключевые кадры...",
        "analyzing": "⏳ Анализирую {n} кадров...",
        "validating": "🔍 Проверяю видео...",
        "err_target_not_found": "❌ Не нашёл игрока с таким описанием на видео.\n\nПроверь цвет одежды или попробуй вариант «Не знаю / разбери обоих».\n\n💳 Кредит не списан.",
        "err_not_badminton": "❌ На видео не похоже на бадминтон.\n\nЯ анализирую только игру и тренировки по бадминтону. Отправь видео с корта 🏸\n\n💳 Кредит не списан.",
        "generating": "⏳ Генерирую PDF отчёт...",
        "done": "✅ Анализ готов, {name}!\n💳 Осталось: {credits} анализов",
        "err_download": "❌ Не смог скачать видео. Попробуй другую ссылку или файл.",
        "err_youtube": "❌ YouTube сейчас не поддерживается (блокирует скачивание).\n\n✅ Отправь видео файлом или ссылкой Google Drive.",
        "err_format": "❌ Не понял формат. Отправь файл или ссылку.",
        "err_frames": "❌ Не удалось извлечь кадры. Попробуй другое видео.",
        "err_timeout": "❌ Анализ занял слишком много времени. Попробуй видео покороче.",
        "err_general": "❌ Ошибка. Нажми «Начать анализ» чтобы попробовать снова.",
        "cancelled": "❌ Отменено.",
        "choose_lang": "🌐 Выберите язык:",
        "lang_set": "✅ Язык установлен: Русский",
        "menu_analyze": "🏸 Анализ",
        "menu_buy": "💳 Купить",
        "menu_balance": "💰 Баланс",
        "menu_language": "🌐 Язык",
        "menu_help": "❓ Помощь",
        "menu_hint": "Выбери действие на клавиатуре ниже 👇",
        "btn_kaspi": "🇰🇿 Оплата Казахстан (Kaspi)",
        "kaspi_info": "🇰🇿 Оплата через Kaspi\n\nЦены:\n{prices}\n\n💳 Kaspi: {kaspi}\n👤 Получатель: {name}\n\n📲 Как оплатить:\n1. Переведи нужную сумму на Kaspi выше\n2. Напиши {admin} и пришли:\n   • скриншот оплаты\n   • свой ID: {uid}\n3. Я начислю анализы в течение пары часов\n\n🆔 Твой ID: {uid}",
        "pack_1": "1 анализ",
        "pack_5": "5 анализов",
        "pack_20": "20 анализов",
        "invoice_title": "RallyIQ — {credits} анализов",
        "invoice_desc": "Пополнение баланса на {credits} анализов матчей/тренировок по бадминтону.",
        "invoice_label": "Анализы RallyIQ",
        "payment_ok": "✅ Оплата прошла! Начислено {credits} анализов.\n💰 Баланс: {balance}",
        "menu_faq": "❓ FAQ / Помощь",
        "onboarding": "🏸 Добро пожаловать в RallyIQ!\n\nЯ — твой AI-тренер по бадминтону. Загрузи видео матча или тренировки, и я разберу твою игру: технику, работу ног, тактику и дам упражнения.\n\n👇 Используй кнопки внизу экрана — всё просто!\n\n🎁 Первый анализ бесплатно.",
        "faq_main": "❓ Частые вопросы\n\nВыбери тему:",
        "faq_btn_drive": "📁 Как загрузить через Google Drive",
        "faq_btn_video": "🎥 Какое видео подходит",
        "faq_btn_how": "⚙️ Как работает анализ",
        "faq_btn_time": "⏱ Сколько ждать",
        "faq_btn_back": "⬅️ Назад",
        "faq_drive": "📁 *Как загрузить через Google Drive*\n\n1. Загрузи видео на drive.google.com\n2. Правый клик на файле → «Поделиться»\n3. В окне доступа выбери «Все, у кого есть ссылка»\n4. Нажми «Копировать ссылку»\n5. Отправь ссылку боту\n\n⚠️ ВАЖНО: без открытого доступа бот не сможет скачать видео!\n\nЕсли доступ «Ограниченный» — поменяй на «Все, у кого есть ссылка».",
        "faq_video": "🎥 *Какое видео подходит*\n\n✅ Хорошо:\n• Камера на штативе или сбоку\n• Видно весь корт и игроков\n• Дневной свет или яркое освещение\n• Клипы 1-2 мин или полные матчи\n\n❌ Плохо:\n• Сильно трясётся\n• Очень тёмное\n• Игроки слишком далеко/мелкие\n\n📁 Файл до 50МБ — прямо в чат\n📁 Больше — через Google Drive",
        "faq_how": "⚙️ *Как работает анализ*\n\n1. Ты отправляешь видео\n2. Указываешь как тебя найти (цвет одежды / позиция)\n3. AI разбирает ключевые моменты игры\n4. Получаешь PDF-отчёт:\n   • Сильные стороны\n   • Технические ошибки\n   • Тактика\n   • Упражнения для тренировки\n\n💡 Анализ основан на AI и может содержать неточности — это помощник, а не замена тренеру.",
        "faq_time": "⏱ *Сколько ждать*\n\nОбычно 3-7 минут после загрузки.\n\nЗависит от:\n• Размера видео\n• Скорости загрузки\n\nБот покажет статус: скачивание → кадры → анализ → отчёт.\n\nЕсли завис дольше 10 минут — напиши заново.",
        "ask_identify": "Как тебя найти на видео? Выбери удобный способ:",
        "btn_by_color": "👕 По цвету одежды",
        "btn_by_position": "📍 По позиции на корте",
        "btn_dont_know": "🤷 Не знаю / разбери обоих",
        "ask_position": "📍 С какой стороны корта ты в начале видео?",
        "btn_near": "⬇️ Ближняя к камере",
        "btn_far": "⬆️ Дальняя от камеры",
        "identify_color": "по цвету одежды: {shirt}",
        "identify_position": "по позиции: {position} сторона корта в начале",
        "identify_both": "оба игрока (анализ обоих)",
        "pos_near": "ближняя к камере",
        "pos_far": "дальняя от камеры",
        "frame_prompt": "Опиши кадр из видео по бадминтону. Только факты.\nАнализируемый игрок определяется так: {target}.\nПиши 'TARGET_NOT_FOUND' ТОЛЬКО если на корте вообще нет игрока даже отдалённо похожего на описание (например указан красный, а все в синем). Если игрок подходит хотя бы примерно или ты не уверен — опиши его. Лучше проанализировать, чем отказать.\nВАЖНО: если игрока с таким описанием (цвет/позиция) НЕТ в кадре — напиши ровно 'target not found'. НЕ выдумывай и НЕ анализируй другого игрока вместо него.\n- Позиция (сетка/середина/задняя линия)\n- Тип удара (смэш/клир/дроп/лифт/подача/нет)\n- Положение ракетки (высоко/низко/замах)\n- Стойка (согнутые колени/прямо/прыжок/выпад)\n- Работа ног и баланс\n- Заметная ошибка если есть\nЕсли нужный игрок не виден — напиши 'not visible'. 2-3 предложения.",
        "report_prompt": "Ты — опытный тренер по бадминтону с 10-летним стажем.\nТы проанализировал {n} кадров. Игрок: {name}. Как определить игрока: {target}.\n\nКАДРЫ:\n{frames}\n\nНапиши детальный отчёт НА РУССКОМ ЯЗЫКЕ строго по структуре.\n\nСАМОЙ ПЕРВОЙ строкой выдай оценки игрока от 0 до 100 в ТОЧНОМ формате (без лишних слов):\nSCORES: общий|работа ног|техника|тактика|позиционирование|восстановление\nНапример: SCORES: 78|82|68|71|74|80\nОценивай реалистично на основе увиденного. Затем с новой строки структура:\n\n## ПРИОРИТЕТ №1\n[Одна самая важная вещь над которой работать прямо сейчас — 2-3 предложения, конкретно и мотивирующе]\n\n## СИЛЬНЫЕ СТОРОНЫ\n1. [наблюдение]\n2. [наблюдение]\n3. [наблюдение]\n\n## ТЕХНИЧЕСКИЕ ОШИБКИ\n1. [ошибка]: [почему это проблема]\n2. [ошибка]: [объяснение]\n3. [ошибка]: [объяснение]\n\n## ТАКТИКА\n1. [паттерн]: [как влияет на игру]\n2. [паттерн]: [описание]\n\n## ТВОЙ УРОВЕНЬ\n[2-3 предложения: на каком уровне игрок сейчас (начинающий/любитель/средний/продвинутый), чего не хватает до следующего уровня]\n\n## УПРАЖНЕНИЯ\n1. [название]: [как выполнять, 2 предложения]\n2. [название]: [описание]\n3. [название]: [описание]\n\n## ПЛАН НА НЕДЕЛЮ\n[Подбери нагрузку по общему баллу: если балл ниже 60 — лёгкий план, фокус на базовой технике без перегрузок; 60-75 — умеренный, техника плюс физподготовка; выше 75 — интенсивнее, тактика и продвинутые упражнения. План должен быть безопасным для любителя.]\nПонедельник: [фокус дня]\nСреда: [фокус дня]\nПятница: [фокус дня]\nВыходные: [фокус дня]\nВажно: прислушивайся к телу, адаптируй нагрузку под свою форму, при боли — остановись.\n\n## ИТОГ\n[3 предложения: уровень, главное что исправить, мотивация]\n\nКРИТИЧЕСКИ ВАЖНО: Весь отчёт ПОЛНОСТЬЮ на РУССКОМ языке, включая заголовки секций. Даже если описания кадров на английском — пиши по-русски.\nВАЖНО: Анализируй на основе того что РЕАЛЬНО видишь в кадрах — стойка, позиция, замах, работа ног, положение на корте. Даже из нескольких кадров можно сделать полезные наблюдения о технике и позиционировании. НЕ пиши 'недостаточно данных' — вместо этого опиши конкретно что видишь и дай практичные советы. Будь конкретным тренером, а не отписывайся.",
        "sections": ["СИЛЬНЫЕ СТОРОНЫ", "ТЕХНИЧЕСКИЕ ОШИБКИ", "ТАКТИКА", "УПРАЖНЕНИЯ", "ИТОГ"],
    },
    "kz": {
        "welcome": "Сәлем, {name}!\n\n🏸 RallyIQ — бадминтон бойынша AI-жаттықтырушың.\n\nМатч бейнесін жүктейсің → талдау аласың:\n• Күшті жақтары\n• Техникалық қателер\n• Тактика\n• Жаттығулар\n\n💳 Баланс: {credits} талдау",
        "help": "🏸 Қалай пайдалану:\n\nТөмендегі батырмаларды бас:\n🏸 Талдау — бейне талдауы\n💳 Сатып алу — талдау пакеттері\n💰 Баланс — қанша қалды\n🌐 Тіл — тілді ауыстыру\n\nБейне форматтары:\n• Файлды тікелей чатқа (50МБ дейін)\n• Google Drive сілтемесі",
        "buy_text": "💳 Талдау пакетін таңда:\n\n⭐ Telegram Stars арқылы төлем.\n🎁 Бірінші талдау тегін.",
        "btn_analyze": "🏸 Талдауды бастау",
        "btn_buy": "💳 Талдау сатып алу",
        "paid_ok": "✅ 5 талдау қосылды!\nБаланс: {credits}",
        "free_ok": "🎁 Тегін талдау қосылды!\n«Талдауды бастау» батырмасын бас.",
        "free_used": "❌ Тегін талдау бұрын пайдаланылды.\n«Талдау сатып алу» батырмасын бас.",
        "balance": "💳 Сенің балансың: {credits} талдау",
        "no_credits": "❌ Талдауларың жоқ.\n\n🎁 Бірінші рет пе? «Талдауды бастау» бас — тегін беремін\n💳 Немесе пакет сатып ал",
        "busy": "⏳ Алдыңғы бейнеңді талдап жатырмын. Нәтижені күт.",
        "ask_shirt": "🏸 Бастаймыз!\n\nОсы бейнедегі киіміңді сипатта:\nМысалы: қызыл футболка, қара шорт",
        "ask_opponent": "✅ Түсіндім: {shirt}\n\nЕнді қарсыластың киімін сипатта:",
        "ask_video": "✅ Керемет!\n\nБейнені жібер:\n1️⃣ Файлды тікелей чатқа (50МБ дейін)\n2️⃣ Google Drive сілтемесі (кез келген өлшем)\n\n💡 Ең жақсысы: 20-60 секунд белсенді ойын, сен анық көрінесің\n💡 Drive: «сілтемесі бар кез келген адамға» рұқсат аш\n\n/cancel — болдырмау",
        "processing": "⏳ Алдым! Талдап жатырмын... 5-10 минут 🎯",
        "downloading": "⏳ Бейнені жүктеп жатырмын...",
        "extracting": "⏳ Негізгі кадрларды шығарып жатырмын...",
        "analyzing": "⏳ {n} кадрды талдап жатырмын...",
        "validating": "🔍 Бейнені тексеріп жатырмын...",
        "err_target_not_found": "❌ Осындай сипаттағы ойыншыны таппадым.\n\nКиім түсін тексер немесе «Білмеймін» таңда.\n\n💳 Кредит алынбады.",
        "err_not_badminton": "❌ Бейнеде бадминтон емес сияқты.\n\nМен тек бадминтонды талдаймын. Корттан бейне жібер 🏸\n\n💳 Кредит алынбады.",
        "generating": "⏳ PDF есеп жасап жатырмын...",
        "done": "✅ Талдау дайын, {name}!\n💳 Қалды: {credits} талдау",
        "err_download": "❌ Бейнені жүктей алмадым. Басқа сілтеме немесе файл жібер.",
        "err_youtube": "❌ YouTube қазір қолдалмайды.\n\n✅ Бейнені файл немесе Google Drive сілтемесімен жібер.",
        "err_format": "❌ Форматты түсінбедім. Файл немесе сілтеме жібер.",
        "err_frames": "❌ Кадрларды шығара алмадым. Басқа бейне жібер.",
        "err_timeout": "❌ Талдау тым ұзаққа созылды. Қысқарақ бейне жібер.",
        "err_general": "❌ Қате. «Талдауды бастау» басып қайта көр.",
        "cancelled": "❌ Болдырылмады.",
        "choose_lang": "🌐 Тілді таңдаңыз:",
        "lang_set": "✅ Тіл орнатылды: Қазақша",
        "menu_analyze": "🏸 Талдау",
        "menu_buy": "💳 Сатып алу",
        "menu_balance": "💰 Баланс",
        "menu_language": "🌐 Тіл",
        "menu_help": "❓ Көмек",
        "menu_hint": "Төмендегі пернетақтадан әрекетті таңда 👇",
        "btn_kaspi": "🇰🇿 Қазақстан төлемі (Kaspi)",
        "kaspi_info": "🇰🇿 Kaspi арқылы төлем\n\nБағалар:\n{prices}\n\n💳 Kaspi: {kaspi}\n👤 Алушы: {name}\n\n📲 Қалай төлеу керек:\n1. Жоғарыдағы Kaspi-ге қажет соманы аудар\n2. {admin} жаз және жібер:\n   • төлем скриншоты\n   • өз ID: {uid}\n3. Мен бірнеше сағатта талдау қосамын\n\n🆔 Сенің ID: {uid}",
        "pack_1": "1 талдау",
        "pack_5": "5 талдау",
        "pack_20": "20 талдау",
        "invoice_title": "RallyIQ — {credits} талдау",
        "invoice_desc": "Бадминтон бойынша {credits} талдауға баланс толтыру.",
        "invoice_label": "RallyIQ талдаулары",
        "payment_ok": "✅ Төлем өтті! {credits} талдау қосылды.\n💰 Баланс: {balance}",
        "menu_faq": "❓ FAQ / Көмек",
        "onboarding": "🏸 RallyIQ-ке қош келдің!\n\nМен — бадминтон бойынша AI-жаттықтырушың. Матч немесе жаттығу бейнесін жүкте, мен ойыныңды талдаймын: техника, аяқ жұмысы, тактика және жаттығулар беремін.\n\n👇 Төмендегі батырмаларды қолдан — бәрі оңай!\n\n🎁 Бірінші талдау тегін.",
        "faq_main": "❓ Жиі қойылатын сұрақтар\n\nТақырыпты таңда:",
        "faq_btn_drive": "📁 Google Drive арқылы қалай жүктеу",
        "faq_btn_video": "🎥 Қандай бейне жарайды",
        "faq_btn_how": "⚙️ Талдау қалай жұмыс істейді",
        "faq_btn_time": "⏱ Қанша күту керек",
        "faq_btn_back": "⬅️ Артқа",
        "faq_drive": "📁 *Google Drive арқылы қалай жүктеу*\n\n1. Бейнені drive.google.com-ға жүкте\n2. Файлға оң жақ түрту → «Бөлісу»\n3. «Сілтемесі бар кез келген адам» таңда\n4. «Сілтемені көшіру» бас\n5. Сілтемені ботқа жібер\n\n⚠️ МАҢЫЗДЫ: ашық рұқсатсыз бот бейнені жүктей алмайды!",
        "faq_video": "🎥 *Қандай бейне жарайды*\n\n✅ Жақсы:\n• Камера штативте немесе бүйірде\n• Барлық корт пен ойыншылар көрінеді\n• Жарық жеткілікті\n• 1-2 мин клиптер немесе толық матчтар\n\n❌ Жаман:\n• Қатты дірілдейді\n• Өте қараңғы\n• Ойыншылар тым алыс\n\n📁 50МБ дейін файл — чатқа\n📁 Үлкенірек — Google Drive арқылы",
        "faq_how": "⚙️ *Талдау қалай жұмыс істейді*\n\n1. Бейне жібересің\n2. Сені қалай табуды көрсетесің\n3. AI ойынның негізгі сәттерін талдайды\n4. PDF есеп аласың:\n   • Күшті жақтар\n   • Қателер\n   • Тактика\n   • Жаттығулар\n\n💡 Талдау AI негізінде, дәл болмауы мүмкін.",
        "faq_time": "⏱ *Қанша күту керек*\n\nӘдетте жүктегеннен кейін 3-7 минут.\n\nБот статусты көрсетеді: жүктеу → кадрлар → талдау → есеп.",
        "ask_identify": "Бейнеде сені қалай табуға болады? Ыңғайлы тәсілді таңда:",
        "btn_by_color": "👕 Киім түсі бойынша",
        "btn_by_position": "📍 Корттағы орны бойынша",
        "btn_dont_know": "🤷 Білмеймін / екеуін де талда",
        "ask_position": "📍 Бейне басында корттың қай жағындасың?",
        "btn_near": "⬇️ Камераға жақын",
        "btn_far": "⬆️ Камерадан алыс",
        "identify_color": "киім түсі бойынша: {shirt}",
        "identify_position": "орны бойынша: басында корттың {position} жағы",
        "identify_both": "екі ойыншы (екеуін де талдау)",
        "pos_near": "камераға жақын",
        "pos_far": "камерадан алыс",
        "frame_prompt": "Бадминтон бейнесінің кадрын сипатта. Тек фактілер.\nТалданатын ойыншы былай анықталады: {target}.\n'TARGET_NOT_FOUND' деп тек кортта сипаттамаға сәл де болса ұқсас ойыншы мүлдем болмаса жаз. Егер ойыншы шамамен сай келсе немесе сенімді болмасаң — оны сипатта. Бас тартқаннан гөрі талдаған жақсы.\nМАҢЫЗДЫ: егер осындай ойыншы (түс/позиция) кадрда БОЛМАСА — дәл 'target not found' деп жаз. Басқа ойыншыны талдама.\n- Позиция (тор/орта/артқы сызық)\n- Соққы түрі (смэш/клир/дроп/лифт/беріліс/жоқ)\n- Ракетка күйі (жоғары/төмен/замах)\n- Тұрыс (иілген тізе/тік/секіріс/ұмтылыс)\n- Аяқ жұмысы мен тепе-теңдік\n- Байқалатын қате болса\nҚажетті ойыншы көрінбесе — 'not visible' деп жаз. 2-3 сөйлем.",
        "report_prompt": "Сен — 10 жылдық тәжірибесі бар бадминтон жаттықтырушысысың.\nСен {n} кадрды талдадың. Ойыншы: {name}. Ойыншыны қалай анықтау: {target}.\n\nКАДРЛАР:\n{frames}\n\nЕҢ БІРІНШІ жолда ойыншы бағаларын 0-100 аралығында ДӘЛ форматта бер:\nSCORES: жалпы|аяқ жұмысы|техника|тактика|позиция|қалпына келу\nМысалы: SCORES: 78|82|68|71|74|80\nСосын жаңа жолдан ҚАЗАҚ ТІЛІНДЕ толық есеп жаз, нақты құрылыммен:\n\n## №1 БАСЫМДЫҚ\n[Дәл қазір жұмыс істеу керек ең маңызды нәрсе — 2-3 сөйлем, нақты әрі ынталандырушы]\n\n## КҮШТІ ЖАҚТАРЫ\n1. [байқау]\n2. [байқау]\n3. [байқау]\n\n## ТЕХНИКАЛЫҚ ҚАТЕЛЕР\n1. [қате]: [неліктен мәселе]\n2. [қате]: [түсіндірме]\n3. [қате]: [түсіндірме]\n\n## ТАКТИКА\n1. [үлгі]: [ойынға әсері]\n2. [үлгі]: [сипаттама]\n\n## СЕНІҢ ДЕҢГЕЙІҢ\n[2-3 сөйлем: ойыншы қазір қай деңгейде, келесі деңгейге не жетіспейді]\n\n## ЖАТТЫҒУЛАР\n1. [атауы]: [қалай орындау, 2 сөйлем]\n2. [атауы]: [сипаттама]\n3. [атауы]: [сипаттама]\n\n## АПТАЛЫҚ ЖОСПАР\n[Жалпы балл бойынша жүктемені таңда: 60-тан төмен — жеңіл, базалық техника; 60-75 — орташа; 75-тен жоғары — қарқынды. Әуесқой үшін қауіпсіз болсын.]\nДүйсенбі: [күн фокусы]\nСәрсенбі: [күн фокусы]\nЖұма: [күн фокусы]\nДемалыс: [күн фокусы]\nМаңызды: денеңді тыңда, жүктемені формаңа бейімде, ауырса — тоқта.\n\n## ҚОРЫТЫНДЫ\n[3 сөйлем: деңгей, ең бастысы не түзету, мотивация]\n\nӨТЕ МАҢЫЗДЫ: Бүкіл есеп ТОЛЫҚ ҚАЗАҚ тілінде, тақырыптарды қоса. Кадр сипаттамалары ағылшынша болса да — қазақша жаз.\nМАҢЫЗДЫ: Кадрларда НАҚТЫ көретініңе сүйеніп талда — тұрыс, позиция, замах, аяқ жұмысы. Бірнеше кадрдан да техника туралы пайдалы байқау жасауға болады. 'Деректер жеткіліксіз' деп жазба — оның орнына нақты не көретініңді сипатта және практикалық кеңес бер.",
        "sections": ["КҮШТІ ЖАҚТАРЫ", "ТЕХНИКАЛЫҚ ҚАТЕЛЕР", "ТАКТИКА", "ЖАТТЫҒУЛАР", "ҚОРЫТЫНДЫ"],
    },
    "en": {
        "welcome": "Hello, {name}!\n\n🏸 RallyIQ — your AI badminton coach.\n\nUpload a match video → get analysis:\n• Strengths\n• Technical mistakes\n• Tactics\n• Drills\n\n💳 Balance: {credits} analyses",
        "help": "🏸 How to use:\n\nTap the buttons below:\n🏸 Analyze — video breakdown\n💳 Buy — analysis packages\n💰 Balance — how many left\n🌐 Language — change language\n\nVideo formats:\n• File directly in chat (up to 50MB)\n• Google Drive link (any size)",
        "buy_text": "💳 Choose an analysis package:\n\n⭐ Pay with Telegram Stars.\n🎁 First analysis is always free.",
        "btn_analyze": "🏸 Start analysis",
        "btn_buy": "💳 Buy analyses",
        "paid_ok": "✅ 5 analyses added!\nBalance: {credits}",
        "free_ok": "🎁 Free analysis added!\nTap «Start analysis».",
        "free_used": "❌ Free analysis already used.\nTap «Buy analyses».",
        "balance": "💳 Your balance: {credits} analyses",
        "no_credits": "❌ You have no analyses.\n\n🎁 First time? Tap «Start analysis» — I'll give one free\n💳 Or buy a package",
        "busy": "⏳ I'm already analyzing your previous video. Please wait.",
        "ask_shirt": "🏸 Let's start!\n\nDescribe your outfit in this video:\nE.g.: red shirt, black shorts",
        "ask_opponent": "✅ Got it: {shirt}\n\nNow describe your opponent's outfit:",
        "ask_video": "✅ Great!\n\nSend your video:\n1️⃣ File directly in chat (up to 50MB)\n2️⃣ Google Drive link (any size)\n\n💡 Best: 20-60 seconds of active play where you are clearly visible\n💡 Drive: set access to «anyone with the link»\n\n/cancel — cancel",
        "processing": "⏳ Got it! Analyzing... 5-10 minutes 🎯",
        "downloading": "⏳ Downloading video...",
        "extracting": "⏳ Extracting key frames...",
        "analyzing": "⏳ Analyzing {n} frames...",
        "validating": "🔍 Checking the video...",
        "err_target_not_found": "❌ I could not find a player matching that description in the video.\n\nCheck the clothing color or try the «Don't know / analyze both» option.\n\n💳 No credit was charged.",
        "err_not_badminton": "❌ This does not look like badminton.\n\nI only analyze badminton matches and training. Please send a video from the court 🏸\n\n💳 No credit was charged.",
        "generating": "⏳ Generating PDF report...",
        "done": "✅ Analysis ready, {name}!\n💳 Left: {credits} analyses",
        "err_download": "❌ Couldn't download video. Try another link or file.",
        "err_youtube": "❌ YouTube is not supported right now (it blocks downloads).\n\n✅ Send the video as a file in chat, or a Google Drive link.",
        "err_format": "❌ Format not recognized. Send a file or link.",
        "err_frames": "❌ Couldn't extract frames. Try another video.",
        "err_timeout": "❌ Analysis took too long. Try a shorter video.",
        "err_general": "❌ Error. Tap «Start analysis» to try again.",
        "cancelled": "❌ Cancelled.",
        "choose_lang": "🌐 Choose your language:",
        "lang_set": "✅ Language set: English",
        "menu_analyze": "🏸 Analyze",
        "menu_buy": "💳 Buy",
        "menu_balance": "💰 Balance",
        "menu_language": "🌐 Language",
        "menu_help": "❓ Help",
        "menu_hint": "Choose an action on the keyboard below 👇",
        "btn_kaspi": "🇰🇿 Pay Kazakhstan (Kaspi)",
        "kaspi_info": "🇰🇿 Payment via Kaspi\n\nPrices:\n{prices}\n\n💳 Kaspi: {kaspi}\n👤 Recipient: {name}\n\n📲 How to pay:\n1. Transfer the amount to the Kaspi above\n2. Message {admin} and send:\n   • payment screenshot\n   • your ID: {uid}\n3. I will add analyses within a couple of hours\n\n🆔 Your ID: {uid}",
        "pack_1": "1 analysis",
        "pack_5": "5 analyses",
        "pack_20": "20 analyses",
        "invoice_title": "RallyIQ — {credits} analyses",
        "invoice_desc": "Top up your balance with {credits} badminton match/training analyses.",
        "invoice_label": "RallyIQ analyses",
        "payment_ok": "✅ Payment successful! {credits} analyses added.\n💰 Balance: {balance}",
        "menu_faq": "❓ FAQ / Help",
        "onboarding": "🏸 Welcome to RallyIQ!\n\nI'm your AI badminton coach. Upload a match or training video and I'll analyze your game: technique, footwork, tactics, and give you drills.\n\n👇 Use the buttons below — it's easy!\n\n🎁 First analysis is free.",
        "faq_main": "❓ Frequently Asked Questions\n\nChoose a topic:",
        "faq_btn_drive": "📁 How to upload via Google Drive",
        "faq_btn_video": "🎥 What video works best",
        "faq_btn_how": "⚙️ How analysis works",
        "faq_btn_time": "⏱ How long it takes",
        "faq_btn_back": "⬅️ Back",
        "faq_drive": "📁 *How to upload via Google Drive*\n\n1. Upload video to drive.google.com\n2. Right-click the file → «Share»\n3. Select «Anyone with the link»\n4. Click «Copy link»\n5. Send the link to the bot\n\n⚠️ IMPORTANT: without open access the bot can't download your video!\n\nIf access is «Restricted» — change it to «Anyone with the link».",
        "faq_video": "🎥 *What video works best*\n\n✅ Good:\n• Camera on a tripod or from the side\n• Whole court and players visible\n• Good lighting\n• 1-2 min clips or full matches\n\n❌ Bad:\n• Very shaky\n• Too dark\n• Players too far/small\n\n📁 File up to 50MB — directly in chat\n📁 Larger — via Google Drive",
        "faq_how": "⚙️ *How analysis works*\n\n1. You send a video\n2. Tell me how to find you (clothing/position)\n3. AI analyzes key moments\n4. You get a PDF report:\n   • Strengths\n   • Technical mistakes\n   • Tactics\n   • Training drills\n\n💡 Analysis is AI-based and may contain inaccuracies — it's a helper, not a replacement for a coach.",
        "faq_time": "⏱ *How long it takes*\n\nUsually 3-7 minutes after upload.\n\nThe bot shows status: downloading → frames → analysis → report.",
        "ask_identify": "How do I find you in the video? Choose a method:",
        "btn_by_color": "👕 By clothing color",
        "btn_by_position": "📍 By court position",
        "btn_dont_know": "🤷 Don't know / analyze both",
        "ask_position": "📍 Which side of the court are you on at the start?",
        "btn_near": "⬇️ Near side (closer to camera)",
        "btn_far": "⬆️ Far side (away from camera)",
        "identify_color": "by clothing color: {shirt}",
        "identify_position": "by position: {position} side at start",
        "identify_both": "both players (analyze both)",
        "pos_near": "near side",
        "pos_far": "far side",
        "frame_prompt": "Describe this badminton video frame. Facts only.\nThe player to analyze is identified by: {target}.\nWrite 'TARGET_NOT_FOUND' ONLY if there is no player even remotely matching the description on court (e.g. red specified but everyone is in blue). If the player roughly matches or you are unsure — describe them. Better to analyze than to refuse.\nIMPORTANT: if a player matching this description (color/position) is NOT present in the frame, write exactly 'target not found'. Do NOT invent or analyze a different player instead.\n- Position (net/mid/baseline)\n- Shot type (smash/clear/drop/lift/serve/none)\n- Racket position (high/low/mid-swing)\n- Stance (bent knees/upright/jumping/lunging)\n- Footwork and balance\n- Any visible mistake\nIf the target player is not visible — write 'not visible'. 2-3 sentences.",
        "report_prompt": "You are an expert badminton coach with 10 years of experience.\nYou analyzed {n} frames. Player: {name}. How to identify the player: {target}.\n\nFRAMES:\n{frames}\n\nThe VERY FIRST line must give player scores from 0 to 100 in EXACT format (no extra words):\nSCORES: overall|footwork|technique|tactics|positioning|recovery\nExample: SCORES: 78|82|68|71|74|80\nScore realistically based on what you saw. Then on a new line write a detailed report IN ENGLISH following this exact structure:\n\n## TOP PRIORITY\n[The single most important thing to work on right now — 2-3 sentences, specific and motivating]\n\n## STRENGTHS\n1. [observation]\n2. [observation]\n3. [observation]\n\n## TECHNICAL MISTAKES\n1. [mistake]: [why it's a problem]\n2. [mistake]: [explanation]\n3. [mistake]: [explanation]\n\n## TACTICS\n1. [pattern]: [how it affects the game]\n2. [pattern]: [description]\n\n## YOUR LEVEL\n[2-3 sentences: what level the player is now (beginner/amateur/intermediate/advanced), what's missing to reach the next level]\n\n## DRILLS\n1. [name]: [how to do it, 2 sentences]\n2. [name]: [description]\n3. [name]: [description]\n\n## WEEKLY PLAN\n[Match the load to the overall score: below 60 — light plan, focus on basic technique, no overload; 60-75 — moderate, technique plus fitness; above 75 — more intense, tactics and advanced drills. Keep it safe for an amateur.]\nMonday: [focus]\nWednesday: [focus]\nFriday: [focus]\nWeekend: [focus]\nImportant: listen to your body, adapt the load to your fitness, stop if you feel pain.\n\n## SUMMARY\n[3 sentences: level, main thing to fix, motivation]\n\nCRITICAL: Write the ENTIRE report in ENGLISH, including section headers.\nIMPORTANT: Analyze based on what you ACTUALLY see in the frames — stance, position, swing, footwork, court positioning. Even from a few frames you can make useful observations about technique and positioning. Do NOT write 'insufficient data' — instead describe specifically what you see and give practical advice. Be a concrete coach, not evasive.",
        "sections": ["STRENGTHS", "TECHNICAL MISTAKES", "TACTICS", "DRILLS", "SUMMARY"],
    },
}


def t(lang: str, key: str, **kwargs) -> str:
    """Возвращает текст по ключу на нужном языке."""
    lang = lang if lang in TEXTS else "ru"
    text = TEXTS[lang].get(key, key)
    return text.format(**kwargs) if kwargs else text
