"""
RallyIQ — все тексты интерфейса на трёх языках.
Казахский написан правильной кириллицей.
"""

TEXTS = {
    "ru": {
        "welcome": "Привет, {name}!\n\n🏸 RallyIQ — твой AI-тренер по бадминтону.\n\nЗагружаешь видео матча → получаешь разбор:\n• Сильные стороны\n• Технические ошибки\n• Тактика\n• Упражнения\n\n💳 Баланс: {credits} анализов",
        "help": "🏸 Как пользоваться:\n\nНажми кнопки внизу экрана:\n🏸 Анализ — разбор видео\n💳 Купить — пакеты анализов\n💰 Баланс — сколько осталось\n🌐 Язык — сменить язык\n\nФорматы видео:\n• Файл прямо в чат (до 50МБ)\n• Google Drive ссылка (любой размер)",
        "buy_text": "💳 Выбери пакет:\n\n🎯 5 анализов — $9.99\n🚀 20 анализов — $19.99",
        "btn_5": "🎯 5 анализов — $9.99",
        "btn_20": "🚀 20 анализов — $19.99",
        "btn_analyze": "🏸 Начать анализ",
        "btn_buy": "💳 Купить анализы",
        "paid_ok": "✅ Добавлено 5 анализов!\nБаланс: {credits}",
        "free_ok": "🎁 Бесплатный анализ добавлен!\nНажми «Начать анализ».",
        "free_used": "❌ Бесплатный анализ уже использован.\nНажми «Купить анализы».",
        "balance": "💳 Твой баланс: {credits} анализов",
        "no_credits": "❌ У тебя нет анализов.\n\n🎁 Первый раз? Жми «Начать анализ» — дам бесплатный\n💳 Или купи пакет",
        "busy": "⏳ Я уже анализирую твоё предыдущее видео. Дождись результата.",
        "ask_shirt": "🏸 Начинаем!\n\nОпиши свою одежду в видео:\nНапример: красная футболка, чёрные шорты",
        "ask_opponent": "✅ Понял: {shirt}\n\nТеперь опиши одежду соперника:",
        "ask_video": "✅ Отлично!\n\nОтправь видео:\n1️⃣ Файл прямо в чат (до 50МБ)\n2️⃣ Google Drive ссылка (любой размер)\n\n💡 Drive: открой доступ «всем у кого есть ссылка»\n\n/cancel — отмена",
        "processing": "⏳ Получил! Анализирую... 5-10 минут 🎯",
        "downloading": "⏳ Скачиваю видео...",
        "extracting": "⏳ Извлекаю ключевые кадры...",
        "analyzing": "⏳ Анализирую {n} кадров...",
        "generating": "⏳ Генерирую PDF отчёт...",
        "done": "✅ Анализ готов, {name}!\n💳 Осталось: {credits} анализов",
        "err_download": "❌ Не смог скачать видео. Попробуй другую ссылку или файл.",
        "err_youtube": "❌ YouTube сейчас не поддерживается (блокирует скачивание).\n\n✅ Отправь видео файлом или ссылкой Google Drive.",
        "err_format": "❌ Не понял формат. Отправь файл или ссылку.",
        "err_frames": "❌ Не удалось извлечь кадры. Попробуй другое видео.",
        "err_timeout": "❌ Анализ занял слишком много времени. Попробуй видео покороче.",
        "err_general": "❌ Ошибка. Нажми «Начать анализ» чтобы попробовать снова.",
        "cancelled": "❌ Отменено.",
        "choose_lang": "🌐 Выберите язык:",
        "lang_set": "✅ Язык установлен: Русский",
        "menu_analyze": "🏸 Анализ",
        "menu_buy": "💳 Купить",
        "menu_balance": "💰 Баланс",
        "menu_language": "🌐 Язык",
        "menu_help": "❓ Помощь",
        "menu_hint": "Выбери действие на клавиатуре ниже 👇",
        "ask_identify": "Как тебя найти на видео? Выбери удобный способ:",
        "btn_by_color": "👕 По цвету одежды",
        "btn_by_position": "📍 По позиции на корте",
        "btn_dont_know": "🤷 Не знаю / разбери обоих",
        "ask_position": "📍 С какой стороны корта ты в начале видео?",
        "btn_near": "⬇️ Ближняя к камере",
        "btn_far": "⬆️ Дальняя от камеры",
        "identify_color": "по цвету одежды: {shirt}",
        "identify_position": "по позиции: {position} сторона корта в начале",
        "identify_both": "оба игрока (анализ обоих)",
        "pos_near": "ближняя к камере",
        "pos_far": "дальняя от камеры",
        "frame_prompt": "Опиши кадр из видео по бадминтону. Только факты.\nАнализируемый игрок определяется так: {target}.\n- Позиция (сетка/середина/задняя линия)\n- Тип удара (смэш/клир/дроп/лифт/подача/нет)\n- Положение ракетки (высоко/низко/замах)\n- Стойка (согнутые колени/прямо/прыжок/выпад)\n- Работа ног и баланс\n- Заметная ошибка если есть\nЕсли нужный игрок не виден — напиши 'not visible'. 2-3 предложения.",
        "report_prompt": "Ты — опытный тренер по бадминтону с 10-летним стажем.\nТы проанализировал {n} кадров. Игрок: {name}. Как определить игрока: {target}.\n\nКАДРЫ:\n{frames}\n\nНапиши детальный отчёт НА РУССКОМ ЯЗЫКЕ строго по структуре:\n\n## СИЛЬНЫЕ СТОРОНЫ\n1. [наблюдение]\n2. [наблюдение]\n3. [наблюдение]\n\n## ТЕХНИЧЕСКИЕ ОШИБКИ\n1. [ошибка]: [почему это проблема]\n2. [ошибка]: [объяснение]\n3. [ошибка]: [объяснение]\n\n## ТАКТИКА\n1. [паттерн]: [как влияет на игру]\n2. [паттерн]: [описание]\n\n## УПРАЖНЕНИЯ\n1. [название]: [как выполнять, 2 предложения]\n2. [название]: [описание]\n3. [название]: [описание]\n\n## ИТОГ\n[3 предложения: уровень, главное что исправить, мотивация]\n\nОснова — только видимые кадры. Если не уверен — 'недостаточно данных'.",
        "sections": ["СИЛЬНЫЕ СТОРОНЫ", "ТЕХНИЧЕСКИЕ ОШИБКИ", "ТАКТИКА", "УПРАЖНЕНИЯ", "ИТОГ"],
    },
    "kz": {
        "welcome": "Сәлем, {name}!\n\n🏸 RallyIQ — бадминтон бойынша AI-жаттықтырушың.\n\nМатч бейнесін жүктейсің → талдау аласың:\n• Күшті жақтары\n• Техникалық қателер\n• Тактика\n• Жаттығулар\n\n💳 Баланс: {credits} талдау",
        "help": "🏸 Қалай пайдалану:\n\nТөмендегі батырмаларды бас:\n🏸 Талдау — бейне талдауы\n💳 Сатып алу — талдау пакеттері\n💰 Баланс — қанша қалды\n🌐 Тіл — тілді ауыстыру\n\nБейне форматтары:\n• Файлды тікелей чатқа (50МБ дейін)\n• Google Drive сілтемесі",
        "buy_text": "💳 Пакетті таңда:\n\n🎯 5 талдау — $9.99\n🚀 20 талдау — $19.99",
        "btn_5": "🎯 5 талдау — $9.99",
        "btn_20": "🚀 20 талдау — $19.99",
        "btn_analyze": "🏸 Талдауды бастау",
        "btn_buy": "💳 Талдау сатып алу",
        "paid_ok": "✅ 5 талдау қосылды!\nБаланс: {credits}",
        "free_ok": "🎁 Тегін талдау қосылды!\n«Талдауды бастау» батырмасын бас.",
        "free_used": "❌ Тегін талдау бұрын пайдаланылды.\n«Талдау сатып алу» батырмасын бас.",
        "balance": "💳 Сенің балансың: {credits} талдау",
        "no_credits": "❌ Талдауларың жоқ.\n\n🎁 Бірінші рет пе? «Талдауды бастау» бас — тегін беремін\n💳 Немесе пакет сатып ал",
        "busy": "⏳ Алдыңғы бейнеңді талдап жатырмын. Нәтижені күт.",
        "ask_shirt": "🏸 Бастаймыз!\n\nОсы бейнедегі киіміңді сипатта:\nМысалы: қызыл футболка, қара шорт",
        "ask_opponent": "✅ Түсіндім: {shirt}\n\nЕнді қарсыластың киімін сипатта:",
        "ask_video": "✅ Керемет!\n\nБейнені жібер:\n1️⃣ Файлды тікелей чатқа (50МБ дейін)\n2️⃣ Google Drive сілтемесі (кез келген өлшем)\n\n💡 Drive: «сілтемесі бар кез келген адамға» рұқсат аш\n\n/cancel — болдырмау",
        "processing": "⏳ Алдым! Талдап жатырмын... 5-10 минут 🎯",
        "downloading": "⏳ Бейнені жүктеп жатырмын...",
        "extracting": "⏳ Негізгі кадрларды шығарып жатырмын...",
        "analyzing": "⏳ {n} кадрды талдап жатырмын...",
        "generating": "⏳ PDF есеп жасап жатырмын...",
        "done": "✅ Талдау дайын, {name}!\n💳 Қалды: {credits} талдау",
        "err_download": "❌ Бейнені жүктей алмадым. Басқа сілтеме немесе файл жібер.",
        "err_youtube": "❌ YouTube қазір қолдалмайды.\n\n✅ Бейнені файл немесе Google Drive сілтемесімен жібер.",
        "err_format": "❌ Форматты түсінбедім. Файл немесе сілтеме жібер.",
        "err_frames": "❌ Кадрларды шығара алмадым. Басқа бейне жібер.",
        "err_timeout": "❌ Талдау тым ұзаққа созылды. Қысқарақ бейне жібер.",
        "err_general": "❌ Қате. «Талдауды бастау» басып қайта көр.",
        "cancelled": "❌ Болдырылмады.",
        "choose_lang": "🌐 Тілді таңдаңыз:",
        "lang_set": "✅ Тіл орнатылды: Қазақша",
        "menu_analyze": "🏸 Талдау",
        "menu_buy": "💳 Сатып алу",
        "menu_balance": "💰 Баланс",
        "menu_language": "🌐 Тіл",
        "menu_help": "❓ Көмек",
        "menu_hint": "Төмендегі пернетақтадан әрекетті таңда 👇",
        "ask_identify": "Бейнеде сені қалай табуға болады? Ыңғайлы тәсілді таңда:",
        "btn_by_color": "👕 Киім түсі бойынша",
        "btn_by_position": "📍 Корттағы орны бойынша",
        "btn_dont_know": "🤷 Білмеймін / екеуін де талда",
        "ask_position": "📍 Бейне басында корттың қай жағындасың?",
        "btn_near": "⬇️ Камераға жақын",
        "btn_far": "⬆️ Камерадан алыс",
        "identify_color": "киім түсі бойынша: {shirt}",
        "identify_position": "орны бойынша: басында корттың {position} жағы",
        "identify_both": "екі ойыншы (екеуін де талдау)",
        "pos_near": "камераға жақын",
        "pos_far": "камерадан алыс",
        "frame_prompt": "Бадминтон бейнесінің кадрын сипатта. Тек фактілер.\nТалданатын ойыншы былай анықталады: {target}.\n- Позиция (тор/орта/артқы сызық)\n- Соққы түрі (смэш/клир/дроп/лифт/беріліс/жоқ)\n- Ракетка күйі (жоғары/төмен/замах)\n- Тұрыс (иілген тізе/тік/секіріс/ұмтылыс)\n- Аяқ жұмысы мен тепе-теңдік\n- Байқалатын қате болса\nҚажетті ойыншы көрінбесе — 'not visible' деп жаз. 2-3 сөйлем.",
        "report_prompt": "Сен — 10 жылдық тәжірибесі бар бадминтон жаттықтырушысысың.\nСен {n} кадрды талдадың. Ойыншы: {name}. Ойыншыны қалай анықтау: {target}.\n\nКАДРЛАР:\n{frames}\n\nҚАЗАҚ ТІЛІНДЕ толық есеп жаз, нақты құрылыммен:\n\n## КҮШТІ ЖАҚТАРЫ\n1. [байқау]\n2. [байқау]\n3. [байқау]\n\n## ТЕХНИКАЛЫҚ ҚАТЕЛЕР\n1. [қате]: [неліктен мәселе]\n2. [қате]: [түсіндірме]\n3. [қате]: [түсіндірме]\n\n## ТАКТИКА\n1. [үлгі]: [ойынға әсері]\n2. [үлгі]: [сипаттама]\n\n## ЖАТТЫҒУЛАР\n1. [атауы]: [қалай орындау, 2 сөйлем]\n2. [атауы]: [сипаттама]\n3. [атауы]: [сипаттама]\n\n## ҚОРЫТЫНДЫ\n[3 сөйлем: деңгей, ең бастысы не түзету, мотивация]\n\nНегіз — тек көрінетін кадрлар. Сенімді болмасаң — 'деректер жеткіліксіз'.",
        "sections": ["КҮШТІ ЖАҚТАРЫ", "ТЕХНИКАЛЫҚ ҚАТЕЛЕР", "ТАКТИКА", "ЖАТТЫҒУЛАР", "ҚОРЫТЫНДЫ"],
    },
    "en": {
        "welcome": "Hello, {name}!\n\n🏸 RallyIQ — your AI badminton coach.\n\nUpload a match video → get analysis:\n• Strengths\n• Technical mistakes\n• Tactics\n• Drills\n\n💳 Balance: {credits} analyses",
        "help": "🏸 How to use:\n\nTap the buttons below:\n🏸 Analyze — video breakdown\n💳 Buy — analysis packages\n💰 Balance — how many left\n🌐 Language — change language\n\nVideo formats:\n• File directly in chat (up to 50MB)\n• Google Drive link (any size)",
        "buy_text": "💳 Choose a package:\n\n🎯 5 analyses — $9.99\n🚀 20 analyses — $19.99",
        "btn_5": "🎯 5 analyses — $9.99",
        "btn_20": "🚀 20 analyses — $19.99",
        "btn_analyze": "🏸 Start analysis",
        "btn_buy": "💳 Buy analyses",
        "paid_ok": "✅ 5 analyses added!\nBalance: {credits}",
        "free_ok": "🎁 Free analysis added!\nTap «Start analysis».",
        "free_used": "❌ Free analysis already used.\nTap «Buy analyses».",
        "balance": "💳 Your balance: {credits} analyses",
        "no_credits": "❌ You have no analyses.\n\n🎁 First time? Tap «Start analysis» — I'll give one free\n💳 Or buy a package",
        "busy": "⏳ I'm already analyzing your previous video. Please wait.",
        "ask_shirt": "🏸 Let's start!\n\nDescribe your outfit in this video:\nE.g.: red shirt, black shorts",
        "ask_opponent": "✅ Got it: {shirt}\n\nNow describe your opponent's outfit:",
        "ask_video": "✅ Great!\n\nSend your video:\n1️⃣ File directly in chat (up to 50MB)\n2️⃣ Google Drive link (any size)\n\n💡 Drive: set access to «anyone with the link»\n\n/cancel — cancel",
        "processing": "⏳ Got it! Analyzing... 5-10 minutes 🎯",
        "downloading": "⏳ Downloading video...",
        "extracting": "⏳ Extracting key frames...",
        "analyzing": "⏳ Analyzing {n} frames...",
        "generating": "⏳ Generating PDF report...",
        "done": "✅ Analysis ready, {name}!\n💳 Left: {credits} analyses",
        "err_download": "❌ Couldn't download video. Try another link or file.",
        "err_youtube": "❌ YouTube is not supported right now (it blocks downloads).\n\n✅ Send the video as a file in chat, or a Google Drive link.",
        "err_format": "❌ Format not recognized. Send a file or link.",
        "err_frames": "❌ Couldn't extract frames. Try another video.",
        "err_timeout": "❌ Analysis took too long. Try a shorter video.",
        "err_general": "❌ Error. Tap «Start analysis» to try again.",
        "cancelled": "❌ Cancelled.",
        "choose_lang": "🌐 Choose your language:",
        "lang_set": "✅ Language set: English",
        "menu_analyze": "🏸 Analyze",
        "menu_buy": "💳 Buy",
        "menu_balance": "💰 Balance",
        "menu_language": "🌐 Language",
        "menu_help": "❓ Help",
        "menu_hint": "Choose an action on the keyboard below 👇",
        "ask_identify": "How do I find you in the video? Choose a method:",
        "btn_by_color": "👕 By clothing color",
        "btn_by_position": "📍 By court position",
        "btn_dont_know": "🤷 Don't know / analyze both",
        "ask_position": "📍 Which side of the court are you on at the start?",
        "btn_near": "⬇️ Near side (closer to camera)",
        "btn_far": "⬆️ Far side (away from camera)",
        "identify_color": "by clothing color: {shirt}",
        "identify_position": "by position: {position} side at start",
        "identify_both": "both players (analyze both)",
        "pos_near": "near side",
        "pos_far": "far side",
        "frame_prompt": "Describe this badminton video frame. Facts only.\nThe player to analyze is identified by: {target}.\n- Position (net/mid/baseline)\n- Shot type (smash/clear/drop/lift/serve/none)\n- Racket position (high/low/mid-swing)\n- Stance (bent knees/upright/jumping/lunging)\n- Footwork and balance\n- Any visible mistake\nIf the target player is not visible — write 'not visible'. 2-3 sentences.",
        "report_prompt": "You are an expert badminton coach with 10 years of experience.\nYou analyzed {n} frames. Player: {name}. How to identify the player: {target}.\n\nFRAMES:\n{frames}\n\nWrite a detailed report IN ENGLISH following this exact structure:\n\n## STRENGTHS\n1. [observation]\n2. [observation]\n3. [observation]\n\n## TECHNICAL MISTAKES\n1. [mistake]: [why it's a problem]\n2. [mistake]: [explanation]\n3. [mistake]: [explanation]\n\n## TACTICS\n1. [pattern]: [how it affects the game]\n2. [pattern]: [description]\n\n## DRILLS\n1. [name]: [how to do it, 2 sentences]\n2. [name]: [description]\n3. [name]: [description]\n\n## SUMMARY\n[3 sentences: level, main thing to fix, motivation]\n\nBase everything on visible frames only. If unsure — 'insufficient data'.",
        "sections": ["STRENGTHS", "TECHNICAL MISTAKES", "TACTICS", "DRILLS", "SUMMARY"],
    },
}


def t(lang: str, key: str, **kwargs) -> str:
    """Возвращает текст по ключу на нужном языке."""
    lang = lang if lang in TEXTS else "ru"
    text = TEXTS[lang].get(key, key)
    return text.format(**kwargs) if kwargs else text
